# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_model.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CreateModel(object):
    def setupUi(self, CreateModel):
        CreateModel.setObjectName("CreateModel")
        CreateModel.resize(412, 287)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreateModel.sizePolicy().hasHeightForWidth())
        CreateModel.setSizePolicy(sizePolicy)
        CreateModel.setWizardStyle(QtWidgets.QWizard.ModernStyle)
        self.wizardPage1 = QtWidgets.QWizardPage()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wizardPage1.sizePolicy().hasHeightForWidth())
        self.wizardPage1.setSizePolicy(sizePolicy)
        self.wizardPage1.setObjectName("wizardPage1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wizardPage1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.wizardPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_a = QtWidgets.QVBoxLayout()
        self.layout_a.setObjectName("layout_a")
        self.verticalLayout_2.addLayout(self.layout_a)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_1 = QtWidgets.QGroupBox(self.wizardPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_1.sizePolicy().hasHeightForWidth())
        self.groupBox_1.setSizePolicy(sizePolicy)
        self.groupBox_1.setObjectName("groupBox_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_b = QtWidgets.QVBoxLayout()
        self.layout_b.setObjectName("layout_b")
        self.verticalLayout.addLayout(self.layout_b)
        self.horizontalLayout.addWidget(self.groupBox_1)
        CreateModel.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wizardPage2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.wizardPage2)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gridHeightNumberOfAtomsLabel = QtWidgets.QLabel(self.groupBox)
        self.gridHeightNumberOfAtomsLabel.setObjectName("gridHeightNumberOfAtomsLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.gridHeightNumberOfAtomsLabel)
        self.gridWidthNumberOfAtomsLabel = QtWidgets.QLabel(self.groupBox)
        self.gridWidthNumberOfAtomsLabel.setObjectName("gridWidthNumberOfAtomsLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.gridWidthNumberOfAtomsLabel)
        self.distanceBetweenAtomsLabel = QtWidgets.QLabel(self.groupBox)
        self.distanceBetweenAtomsLabel.setObjectName("distanceBetweenAtomsLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.distanceBetweenAtomsLabel)
        self.distanceBetweenAtoms = QtWidgets.QLineEdit(self.groupBox)
        self.distanceBetweenAtoms.setClearButtonEnabled(False)
        self.distanceBetweenAtoms.setObjectName("distanceBetweenAtoms")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.distanceBetweenAtoms)
        self.gridWidth = QtWidgets.QSpinBox(self.groupBox)
        self.gridWidth.setMaximum(100000000)
        self.gridWidth.setSingleStep(20)
        self.gridWidth.setProperty("value", 100)
        self.gridWidth.setObjectName("gridWidth")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gridWidth)
        self.gridHeight = QtWidgets.QSpinBox(self.groupBox)
        self.gridHeight.setMaximum(100000000)
        self.gridHeight.setSingleStep(20)
        self.gridHeight.setProperty("value", 100)
        self.gridHeight.setObjectName("gridHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.gridHeight)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.wizardPage2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.firstSpeciesMoleFractionLabel = QtWidgets.QLabel(self.groupBox_3)
        self.firstSpeciesMoleFractionLabel.setObjectName("firstSpeciesMoleFractionLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.firstSpeciesMoleFractionLabel)
        self.firstSpeciesMoleFraction = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.firstSpeciesMoleFraction.setMaximum(1.0)
        self.firstSpeciesMoleFraction.setSingleStep(0.1)
        self.firstSpeciesMoleFraction.setProperty("value", 1.0)
        self.firstSpeciesMoleFraction.setObjectName("firstSpeciesMoleFraction")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.firstSpeciesMoleFraction)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        CreateModel.addPage(self.wizardPage2)
        self.gridHeightNumberOfAtomsLabel.setBuddy(self.gridHeight)
        self.gridWidthNumberOfAtomsLabel.setBuddy(self.gridWidth)
        self.distanceBetweenAtomsLabel.setBuddy(self.distanceBetweenAtoms)
        self.firstSpeciesMoleFractionLabel.setBuddy(self.firstSpeciesMoleFraction)

        self.retranslateUi(CreateModel)
        QtCore.QMetaObject.connectSlotsByName(CreateModel)
        CreateModel.setTabOrder(self.gridWidth, self.gridHeight)
        CreateModel.setTabOrder(self.gridHeight, self.distanceBetweenAtoms)
        CreateModel.setTabOrder(self.distanceBetweenAtoms, self.firstSpeciesMoleFraction)

    def retranslateUi(self, CreateModel):
        _translate = QtCore.QCoreApplication.translate
        CreateModel.setWindowTitle(_translate("CreateModel", "Create Model"))
        self.wizardPage1.setTitle(_translate("CreateModel", "Species definition"))
        self.groupBox_2.setTitle(_translate("CreateModel", "First species"))
        self.groupBox_1.setTitle(_translate("CreateModel", "Second species"))
        self.wizardPage2.setTitle(_translate("CreateModel", "Spatial configuration"))
        self.groupBox.setTitle(_translate("CreateModel", "Grid"))
        self.gridHeightNumberOfAtomsLabel.setText(_translate("CreateModel", "Grid height (number of atoms)"))
        self.gridWidthNumberOfAtomsLabel.setText(_translate("CreateModel", "Grid width (number of atoms)"))
        self.distanceBetweenAtomsLabel.setText(_translate("CreateModel", "Distance between atoms"))
        self.groupBox_3.setTitle(_translate("CreateModel", "Mixup"))
        self.firstSpeciesMoleFractionLabel.setText(_translate("CreateModel", "First species mole fraction"))

