# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'define_external_forces.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExternalForces(object):
    def setupUi(self, ExternalForces):
        ExternalForces.setObjectName("ExternalForces")
        ExternalForces.resize(393, 288)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExternalForces)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upGroupBox = QtWidgets.QGroupBox(ExternalForces)
        self.upGroupBox.setObjectName("upGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.upGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.fractionOfSpaceLabel = QtWidgets.QLabel(self.upGroupBox)
        self.fractionOfSpaceLabel.setObjectName("fractionOfSpaceLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fractionOfSpaceLabel)
        self.fractionOfSpaceDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.upGroupBox)
        self.fractionOfSpaceDoubleSpinBox.setMaximum(1.0)
        self.fractionOfSpaceDoubleSpinBox.setSingleStep(0.01)
        self.fractionOfSpaceDoubleSpinBox.setProperty("value", 0.05)
        self.fractionOfSpaceDoubleSpinBox.setObjectName("fractionOfSpaceDoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fractionOfSpaceDoubleSpinBox)
        self.lowerLimitMLabel = QtWidgets.QLabel(self.upGroupBox)
        self.lowerLimitMLabel.setObjectName("lowerLimitMLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lowerLimitMLabel)
        self.lowerLimitMLineEdit = QtWidgets.QLineEdit(self.upGroupBox)
        self.lowerLimitMLineEdit.setObjectName("lowerLimitMLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lowerLimitMLineEdit)
        self.applyExternalForceLabel = QtWidgets.QLabel(self.upGroupBox)
        self.applyExternalForceLabel.setObjectName("applyExternalForceLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.applyExternalForceLabel)
        self.applyExternalForceCheckBox = QtWidgets.QCheckBox(self.upGroupBox)
        self.applyExternalForceCheckBox.setObjectName("applyExternalForceCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.applyExternalForceCheckBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.widget = QtWidgets.QWidget(self.upGroupBox)
        self.widget.setEnabled(False)
        self.widget.setObjectName("widget")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.xForceComponentPerAtomNLabel = QtWidgets.QLabel(self.widget)
        self.xForceComponentPerAtomNLabel.setObjectName("xForceComponentPerAtomNLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.xForceComponentPerAtomNLabel)
        self.yForceComponentPerAtomNLabel = QtWidgets.QLabel(self.widget)
        self.yForceComponentPerAtomNLabel.setObjectName("yForceComponentPerAtomNLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yForceComponentPerAtomNLabel)
        self.xForceComponentPerAtomNLineEdit = QtWidgets.QLineEdit(self.widget)
        self.xForceComponentPerAtomNLineEdit.setObjectName("xForceComponentPerAtomNLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.xForceComponentPerAtomNLineEdit)
        self.yForceComponentPerAtomNLineEdit = QtWidgets.QLineEdit(self.widget)
        self.yForceComponentPerAtomNLineEdit.setObjectName("yForceComponentPerAtomNLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.yForceComponentPerAtomNLineEdit)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout.addWidget(self.upGroupBox)
        self.lowGroupBox = QtWidgets.QGroupBox(ExternalForces)
        self.lowGroupBox.setObjectName("lowGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.lowGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.fractionOfSpaceLabel_2 = QtWidgets.QLabel(self.lowGroupBox)
        self.fractionOfSpaceLabel_2.setObjectName("fractionOfSpaceLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fractionOfSpaceLabel_2)
        self.fractionOfSpaceDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.lowGroupBox)
        self.fractionOfSpaceDoubleSpinBox_2.setMaximum(1.0)
        self.fractionOfSpaceDoubleSpinBox_2.setSingleStep(0.01)
        self.fractionOfSpaceDoubleSpinBox_2.setProperty("value", 0.05)
        self.fractionOfSpaceDoubleSpinBox_2.setObjectName("fractionOfSpaceDoubleSpinBox_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fractionOfSpaceDoubleSpinBox_2)
        self.upperLimitMLabel = QtWidgets.QLabel(self.lowGroupBox)
        self.upperLimitMLabel.setObjectName("upperLimitMLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.upperLimitMLabel)
        self.upperLimitMLineEdit = QtWidgets.QLineEdit(self.lowGroupBox)
        self.upperLimitMLineEdit.setObjectName("upperLimitMLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.upperLimitMLineEdit)
        self.blockLabel = QtWidgets.QLabel(self.lowGroupBox)
        self.blockLabel.setObjectName("blockLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.blockLabel)
        self.blockCheckBox = QtWidgets.QCheckBox(self.lowGroupBox)
        self.blockCheckBox.setObjectName("blockCheckBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.blockCheckBox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout.addWidget(self.lowGroupBox)

        self.retranslateUi(ExternalForces)
        QtCore.QMetaObject.connectSlotsByName(ExternalForces)

    def retranslateUi(self, ExternalForces):
        _translate = QtCore.QCoreApplication.translate
        self.upGroupBox.setTitle(_translate("ExternalForces", "Upper zone (y+)"))
        self.fractionOfSpaceLabel.setText(_translate("ExternalForces", "Fraction of space"))
        self.lowerLimitMLabel.setText(_translate("ExternalForces", "Lower limit (m)"))
        self.applyExternalForceLabel.setText(_translate("ExternalForces", "Apply external force"))
        self.xForceComponentPerAtomNLabel.setText(_translate("ExternalForces", "x force component per atom (N)"))
        self.yForceComponentPerAtomNLabel.setText(_translate("ExternalForces", "y force component per atom (N)"))
        self.xForceComponentPerAtomNLineEdit.setText(_translate("ExternalForces", "0"))
        self.yForceComponentPerAtomNLineEdit.setText(_translate("ExternalForces", "0"))
        self.lowGroupBox.setTitle(_translate("ExternalForces", "Lower zone (y-)"))
        self.fractionOfSpaceLabel_2.setText(_translate("ExternalForces", "Fraction of space"))
        self.upperLimitMLabel.setText(_translate("ExternalForces", "Upper limit (m)"))
        self.blockLabel.setText(_translate("ExternalForces", "Block"))

